name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Install dependencies
      run: yarn install

  test:
    needs: build

    - name: Run tests
      run: yarn run test

  coverage:
    needs: test

    - name: Code coverage
      run: npx codecov
